# This file is part of the standard setup for testthat.
# It is recommended that you do not modify it.
#
# Where should you do additional test configuration?
# Learn more about the roles of various files in:
# * https://r-pkgs.org/testing-design.html#sec-tests-files-overview
# * https://testthat.r-lib.org/articles/special-files.html

library(testthat)
library(c(`Absentee-Shawnee Tribe of Indians of Oklahoma` = "TADAShinyAnalyze", `Alabama Department of Environmental Management` = "21AWIC", Alaska = "AKDECWQ", `American Samoa` = "21AS", Arizona = "21ARIZ", Arkansas = "ARDEQH2O", `Assiniboine and Sioux Tribes of the Fort Peck Indian Reservation, Montana` = "FORTPECK", `Big Valley Band of Pomo Indians of the Big Valley Rancheria, California` = "CA_BVR", `Blackfeet Tribe of the Blackfeet Indian Reservation of Montana` = "BLCKFEET", `Caddo Nation of Oklahoma` = "CADDONATION", 
California = "CA_SWRCB", `Cherokee Nation` = "CHEROKEE", `Citizen Potawatomi Nation, Oklahoma` = "CPNWATER", Colorado = "21COL001", `Comanche Nation, Oklahoma` = "CNWQD", Connecticut = "CT_DEP01", Delaware = "21DELAWQ", `Delaware Nation, Oklahoma` = "DELAWARENATION", `District of Columbia` = "DOEE", EPA = "USEPA", `Eastern Band of Cherokee Indians` = "EBCI", `Eastern Shawnee Tribe of Oklahoma` = "ESTO", Florida = "21FL303D", `Fort Belknap Indian Community of the Fort Belknap Reservation of Montana` = "FTBLKNAP", 
`Fort Sill Apache` = "FSAWQP", `Georgia Environmental Protection Division` = "21GAEPD", Guam = "21GUAM", Hawaii = "21HI", `Hoopa Valley Tribe, California` = "HVTEPA", Idaho = "IDEQ", Illinois = "IL_EPA", Indiana = "21IND", Iowa = "21IOWA", `Iowa Tribe of Oklahoma` = "IOWATROK", Kansas = "21KAN001", `Kaw Nation, Oklahoma` = "KAWNATON", Kentucky = "21KY", `Kickapoo Tribe of Oklahoma` = "KICKAPOO", `Lac du Flambeau Band of Lake Superior Chippewa Indians of the Lac du Flambeau Reservation of Wisconsin` = "LDFWATER2007", 
`Little River Band of Ottawa Indians, Michigan` = "LRBOI", Louisiana = "LADEQWPD", Maine = "MEDEP", Maryland = "MDE_EASP", Massachusetts = "MA_DEP", `Meskwaki Department of Natural Resources` = "MESKWAKI_DNR", Michigan = "21MICH", Minnesota = "MNPCA", `Minnesota Chippewa Tribe, Minnesota (Fond du Lac Band)` = "FONDULAC", `Minnesota Chippewa Tribe, Minnesota (Grand Portage Band)` = "GPORTAGE", Mississippi = "21MSWQ", Missouri = "MDNR", Montana = "MTDEQ", `N.C. Dept. of Environmental Quality` = "21NC01WQ", 
`Navajo Nation, Arizona, New Mexico, & Utah` = "NNEPA", Nebraska = "21NEB001", Nevada = "21NEV1", `New Hampshire` = "11113300", `New Jersey` = "21NJDEP1", `New Mexico` = "21NMEX", `New York` = "21NYDECA", `North Dakota` = "21NDHDWQ", `Northern Mariana Islands` = "21AQ", Ohio = "21OHIO", Oklahoma = "OKDEQ", Oregon = "OREGONDEQ", `Otoe Missouria Tribe` = "O_MTRIBE", `Ottawa Tribe of Oklahoma` = "OTTAWATRIBEOFOK", Pennsylvania = "21PA", `Penobscot Nation` = "PENOBSCOTINDIANNATIONDNR", `Pueblo of Laguna, New Mexico` = "POLSWATER", 
`Pueblo of Pojoaque, New Mexico` = "PUEBLO_POJOAQUE", `Pueblo of San Ildefonso, New Mexico` = "SANILDEFONSODECP", `Pueblo of Santa Ana, New Mexico` = "PUEBLO_SANTAANA", `Pueblo of Taos, New Mexico` = "TAOSPBLO", `Pueblo of Tesuque, New Mexico` = "PUEBLOOFTESUQUE", `Puerto Rico` = "PR_LAKES", `Pyramid Lake Paiute Tribe of the Pyramid Lake Reservation, Nevada` = "PYRAMIDLAKE", `Red Lake Band of Chippewa Indians, Minnesota` = "REDLAKE", `Rhode Island` = "RIDEM", `Sac & Fox Nation, Oklahoma` = "SFNOES", 
`Saginaw Chippewa Indian Tribe of Michigan` = "SAGIN01", `Saint Regis Mohawk Tribe` = "SRMTWRP", `Seneca-Cayuga Nation` = "SCEQ", `South Carolina` = "21SC60WQ", `South Dakota` = "SDDENR", Tennessee = "TDECWR", Texas = "TCEQMAIN", `The Chickasaw Nation` = "CNENVSER", `The Choctaw Nation of Oklahoma` = "CHOCNAT", `US Virgin Islands` = "USVIST", Utah = "UTAHDWQ", `Ute Mountain Ute Tribe` = "UTEMTN", Vermont = "1VTDECWQ", Virginia = "21VASWCB", `Wampanoag Tribe of Gay Head (Aquinnah)` = "AQUINNAH", Washington = "WA_ECOLOGY", 
`West Virginia` = "WVDEP", Wisconsin = "WIDNR", `Wyandotte Nation` = "WNENVDPT", Wyoming = "WYDEQ"))

test_check("c(`Absentee-Shawnee Tribe of Indians of Oklahoma` = "TADAShinyAnalyze", `Alabama Department of Environmental Management` = "21AWIC", Alaska = "AKDECWQ", `American Samoa` = "21AS", Arizona = "21ARIZ", Arkansas = "ARDEQH2O", `Assiniboine and Sioux Tribes of the Fort Peck Indian Reservation, Montana` = "FORTPECK", `Big Valley Band of Pomo Indians of the Big Valley Rancheria, California` = "CA_BVR", `Blackfeet Tribe of the Blackfeet Indian Reservation of Montana` = "BLCKFEET", `Caddo Nation of Oklahoma` = "CADDONATION", 
California = "CA_SWRCB", `Cherokee Nation` = "CHEROKEE", `Citizen Potawatomi Nation, Oklahoma` = "CPNWATER", Colorado = "21COL001", `Comanche Nation, Oklahoma` = "CNWQD", Connecticut = "CT_DEP01", Delaware = "21DELAWQ", `Delaware Nation, Oklahoma` = "DELAWARENATION", `District of Columbia` = "DOEE", EPA = "USEPA", `Eastern Band of Cherokee Indians` = "EBCI", `Eastern Shawnee Tribe of Oklahoma` = "ESTO", Florida = "21FL303D", `Fort Belknap Indian Community of the Fort Belknap Reservation of Montana` = "FTBLKNAP", 
`Fort Sill Apache` = "FSAWQP", `Georgia Environmental Protection Division` = "21GAEPD", Guam = "21GUAM", Hawaii = "21HI", `Hoopa Valley Tribe, California` = "HVTEPA", Idaho = "IDEQ", Illinois = "IL_EPA", Indiana = "21IND", Iowa = "21IOWA", `Iowa Tribe of Oklahoma` = "IOWATROK", Kansas = "21KAN001", `Kaw Nation, Oklahoma` = "KAWNATON", Kentucky = "21KY", `Kickapoo Tribe of Oklahoma` = "KICKAPOO", `Lac du Flambeau Band of Lake Superior Chippewa Indians of the Lac du Flambeau Reservation of Wisconsin` = "LDFWATER2007", 
`Little River Band of Ottawa Indians, Michigan` = "LRBOI", Louisiana = "LADEQWPD", Maine = "MEDEP", Maryland = "MDE_EASP", Massachusetts = "MA_DEP", `Meskwaki Department of Natural Resources` = "MESKWAKI_DNR", Michigan = "21MICH", Minnesota = "MNPCA", `Minnesota Chippewa Tribe, Minnesota (Fond du Lac Band)` = "FONDULAC", `Minnesota Chippewa Tribe, Minnesota (Grand Portage Band)` = "GPORTAGE", Mississippi = "21MSWQ", Missouri = "MDNR", Montana = "MTDEQ", `N.C. Dept. of Environmental Quality` = "21NC01WQ", 
`Navajo Nation, Arizona, New Mexico, & Utah` = "NNEPA", Nebraska = "21NEB001", Nevada = "21NEV1", `New Hampshire` = "11113300", `New Jersey` = "21NJDEP1", `New Mexico` = "21NMEX", `New York` = "21NYDECA", `North Dakota` = "21NDHDWQ", `Northern Mariana Islands` = "21AQ", Ohio = "21OHIO", Oklahoma = "OKDEQ", Oregon = "OREGONDEQ", `Otoe Missouria Tribe` = "O_MTRIBE", `Ottawa Tribe of Oklahoma` = "OTTAWATRIBEOFOK", Pennsylvania = "21PA", `Penobscot Nation` = "PENOBSCOTINDIANNATIONDNR", `Pueblo of Laguna, New Mexico` = "POLSWATER", 
`Pueblo of Pojoaque, New Mexico` = "PUEBLO_POJOAQUE", `Pueblo of San Ildefonso, New Mexico` = "SANILDEFONSODECP", `Pueblo of Santa Ana, New Mexico` = "PUEBLO_SANTAANA", `Pueblo of Taos, New Mexico` = "TAOSPBLO", `Pueblo of Tesuque, New Mexico` = "PUEBLOOFTESUQUE", `Puerto Rico` = "PR_LAKES", `Pyramid Lake Paiute Tribe of the Pyramid Lake Reservation, Nevada` = "PYRAMIDLAKE", `Red Lake Band of Chippewa Indians, Minnesota` = "REDLAKE", `Rhode Island` = "RIDEM", `Sac & Fox Nation, Oklahoma` = "SFNOES", 
`Saginaw Chippewa Indian Tribe of Michigan` = "SAGIN01", `Saint Regis Mohawk Tribe` = "SRMTWRP", `Seneca-Cayuga Nation` = "SCEQ", `South Carolina` = "21SC60WQ", `South Dakota` = "SDDENR", Tennessee = "TDECWR", Texas = "TCEQMAIN", `The Chickasaw Nation` = "CNENVSER", `The Choctaw Nation of Oklahoma` = "CHOCNAT", `US Virgin Islands` = "USVIST", Utah = "UTAHDWQ", `Ute Mountain Ute Tribe` = "UTEMTN", Vermont = "1VTDECWQ", Virginia = "21VASWCB", `Wampanoag Tribe of Gay Head (Aquinnah)` = "AQUINNAH", Washington = "WA_ECOLOGY", 
`West Virginia` = "WVDEP", Wisconsin = "WIDNR", `Wyandotte Nation` = "WNENVDPT", Wyoming = "WYDEQ")")
